# Generated by Django 4.1.7 on 2023-03-05 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='github_link',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
