# Generated by Django 4.1.7 on 2023-03-06 15:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0002_projet_github_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['is_read', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='projet',
            name='origines',
            field=models.CharField(choices=[('OP', 'Openclassroom'), ('Perso', 'Personnel'), ('Pro', 'Professionnel')], max_length=9),
        ),
    ]
