# Generated by Django 4.1.7 on 2023-04-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0003_message_alter_projet_origines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='origines',
            field=models.CharField(choices=[('OC', 'Openclassroom'), ('Perso', 'Personnel'), ('Pro', 'Professionnel')], max_length=9),
        ),
    ]
